//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopBannerCountdown.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("距离高考还有|天")]
        public string TitleTextA {
            get {
                return ((string)(this["TitleTextA"]));
            }
            set {
                this["TitleTextA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("微软雅黑")]
        public string TitleFontFamily {
            get {
                return ((string)(this["TitleFontFamily"]));
            }
            set {
                this["TitleFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double TitleFontSize {
            get {
                return ((double)(this["TitleFontSize"]));
            }
            set {
                this["TitleFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color TitleForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["TitleForeground"]));
            }
            set {
                this["TitleForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Circular Sp UI T Bold")]
        public string CounterFontFamily {
            get {
                return ((string)(this["CounterFontFamily"]));
            }
            set {
                this["CounterFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double CounterFontSize {
            get {
                return ((double)(this["CounterFontSize"]));
            }
            set {
                this["CounterFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF169141")]
        public global::System.Windows.Media.Color CounterNormalForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["CounterNormalForeground"]));
            }
            set {
                this["CounterNormalForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06/06/2022 08:00:00")]
        public global::System.DateTime DestinationDateA {
            get {
                return ((global::System.DateTime)(this["DestinationDateA"]));
            }
            set {
                this["DestinationDateA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06/08/2022 15:00:00")]
        public global::System.DateTime DestinationDateB {
            get {
                return ((global::System.DateTime)(this["DestinationDateB"]));
            }
            set {
                this["DestinationDateB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("距离解放还有|天")]
        public string TitleTextB {
            get {
                return ((string)(this["TitleTextB"]));
            }
            set {
                this["TitleTextB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DecimalPlaces {
            get {
                return ((int)(this["DecimalPlaces"]));
            }
            set {
                this["DecimalPlaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#99808080")]
        public global::System.Windows.Media.Color WindowBorderBrush {
            get {
                return ((global::System.Windows.Media.Color)(this["WindowBorderBrush"]));
            }
            set {
                this["WindowBorderBrush"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,5")]
        public global::System.Windows.Thickness WindowBorderThickness {
            get {
                return ((global::System.Windows.Thickness)(this["WindowBorderThickness"]));
            }
            set {
                this["WindowBorderThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10,10,10,10")]
        public global::System.Windows.CornerRadius WindowCornerRadius {
            get {
                return ((global::System.Windows.CornerRadius)(this["WindowCornerRadius"]));
            }
            set {
                this["WindowCornerRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int CounterDecimalFontSize {
            get {
                return ((int)(this["CounterDecimalFontSize"]));
            }
            set {
                this["CounterDecimalFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color CounterEmergencyForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["CounterEmergencyForeground"]));
            }
            set {
                this["CounterEmergencyForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SwitchByLeftClick {
            get {
                return ((bool)(this["SwitchByLeftClick"]));
            }
            set {
                this["SwitchByLeftClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SwitchByDoubleClick {
            get {
                return ((bool)(this["SwitchByDoubleClick"]));
            }
            set {
                this["SwitchByDoubleClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TopMost {
            get {
                return ((bool)(this["TopMost"]));
            }
            set {
                this["TopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#99E9E9E9")]
        public global::System.Windows.Media.Color WindowBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["WindowBackground"]));
            }
            set {
                this["WindowBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public double CounterDecimalWidth {
            get {
                return ((double)(this["CounterDecimalWidth"]));
            }
            set {
                this["CounterDecimalWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25,10,25,10")]
        public global::System.Windows.Thickness WindowPadding {
            get {
                return ((global::System.Windows.Thickness)(this["WindowPadding"]));
            }
            set {
                this["WindowPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int EmergencyDays {
            get {
                return ((int)(this["EmergencyDays"]));
            }
            set {
                this["EmergencyDays"] = value;
            }
        }
    }
}
